#!/bin/sh

ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/pryrc ~/.pryrc
echo "source ~/dotfiles/zshrc" >> ~/.zshrc

if [ $SPIN ]; then
  sudo apt-get install -y git-absorb
fi
